platformName: android
platformVersion: 5.1.1
deviceName: 127.0.0.1:62001
appPackage: com.emicro.emicrophone
appActivity: com.emicro.emicrophone.MainActivity
noReset: False
appName: mht_phone.apk
appiumIp: 127.0.0.1
appiumPort: 4723
unicodeKeyboard: true
resetKeyboard: true